spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: qwerty-123
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml