spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

key:
  access: Ws9n8o7ICr7NEmduNZTOi1AKtxRZflHwybQ11tcdtN8=
  refresh: wbHZNJr/QF07z0i58Aa+j/WXdvMTRqVj3bWQ91Ja1Zs=

logging:
  file:
    name: logs/app.log
  level:
    root: warn

messages:
  hello: Hello from Digital Ocean application!